// Real Chromium against ONLY the disposable local production server.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { execSync } from 'node:child_process';
import { chromium } from 'playwright';
if(process.env.DATABASE_URL)throw Error('Remote DB forbidden');
const {default:c}=await import(process.env.QA_CHROMIUM_MODULE);
const dir=process.env.QA_EVIDENCE_DIR||'.cache/pre-f1-polish';await fs.mkdir(dir,{recursive:true});
const report={head:execSync('git rev-parse HEAD').toString().trim(),checks:[],failures:[],console:[],network:[],screens:[]};
const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(x=>x!=='--single-process'),ignoreDefaultArgs:['--hide-scrollbars']});
const p=await browser.newPage({viewport:{width:1440,height:1100},locale:'pt-BR'});p.setDefaultTimeout(12000);
p.on('pageerror',e=>report.console.push(String(e)));p.on('console',e=>{if(e.type()==='error')report.console.push(e.text())});p.on('response',r=>{if(r.status()>=400)report.network.push({url:r.url(),status:r.status()})});
const b='andrioni-vet-qa',base='http://127.0.0.1:3000';
async function go(route){await p.goto(`${base}/${route}${route.includes('?')?'&':'?'}b=${b}`);}
async function shot(name){await p.screenshot({path:`${dir}/${name}.png`});report.screens.push(name+'.png')}
async function test(name,fn){if(process.env.QA_ONLY&&!name.includes(process.env.QA_ONLY))return;try{await fn();report.checks.push(name);console.log('PASS',name)}catch(e){report.failures.push({name,error:String(e),stack:e.stack});console.error('FAIL',name,String(e));await shot('FAIL-'+name.replace(/\W/g,'-')).catch(()=>{})}}
async function agenda(date='2026-11-16'){await go(`agenda?data=${date}&view=day`);await p.locator('[data-agenda-column]').first().waitFor()}
async function gesture(start,end){const box=await p.locator('[data-agenda-column-professional="pro-michele"]').boundingBox();await p.mouse.move(box.x+50,box.y+(start-480)*128/60);await p.mouse.down();if(end)await p.mouse.move(box.x+50,box.y+(end-480)*128/60,{steps:25});await p.mouse.up();await p.getByRole('heading',{name:'Novo agendamento',exact:true}).waitFor()}
const summary=()=>p.getByTestId('booking-range-summary');
async function readApi(url){return p.evaluate(async u=>{const r=await fetch(u);if(!r.ok)throw Error('HTTP '+r.status);return r.json()},url)}
await p.goto(base+'/login');await p.locator('[type=email]').fill('owner.qa@godoutor.local');await p.locator('[type=password]').fill('GodoutorQA2026!');await p.getByRole('button',{name:'Entrar',exact:true}).click();await p.waitForURL(/agenda|dashboard/);
try{
 await test('Michelle dermatology drag195 and click30 split all widths',async()=>{
  for(const width of [1440,1280,1024,390]){
   await p.setViewportSize({width:width===390?1024:width,height:1100});await agenda();await gesture(645,840);
   await p.getByLabel('2. Serviço',{exact:false}).selectOption({label:'Consulta dermatológica · 30 min'});await p.getByText('Verificando disponibilidade…',{exact:true}).waitFor({state:'hidden'});
   assert.match(await summary().innerText(),/Início\s+10:45\s+Fim\s+14:00\s+Duração\s+195 min · 3h15/);
   assert.equal(await p.getByRole('button',{name:'09:00',exact:true}).count(),0);assert.equal(await p.getByLabel('Duração deste atendimento em minutos').isVisible(),false);
   if(width===390)await p.setViewportSize({width,height:844});else{const r=await p.getByTestId('agenda-selected-range').boundingBox(),s=await p.locator('.gd-booking-range-drawer .il-drawer__strip').boundingBox();assert.ok(r.x+r.width<s.x)}
   await shot('drag195-'+width);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
   await p.getByRole('button',{name:'Alterar horário',exact:true}).click();await p.getByRole('button',{name:'10:45',exact:true}).waitFor();assert.match(await summary().innerText(),/10:45/);await shot('alterar-horario-'+width);
   await p.getByRole('button',{name:'Manter horário selecionado',exact:true}).click();assert.equal(await p.getByRole('button',{name:'10:45',exact:true}).count(),0);
  }
  await p.setViewportSize({width:1440,height:1100});await agenda();await gesture(645);
  await p.getByLabel('2. Serviço',{exact:false}).selectOption({label:'Consulta dermatológica · 30 min'});await p.getByRole('button',{name:'10:45',exact:true}).waitFor();assert.match(await summary().innerText(),/10:45\s+Fim\s+11:15\s+Duração\s+30 min/);await shot('click30');
  await agenda();await gesture(645,840);await p.getByLabel('2. Serviço',{exact:false}).selectOption({label:'Consulta dermatológica · 30 min'});await p.getByRole('searchbox',{name:'Buscar cliente'}).fill('Ana');await p.getByRole('button',{name:/Ana Tutora QA/}).click();await p.getByLabel('Pet (paciente)',{exact:false}).selectOption('qa-pet');await p.getByText('Verificando disponibilidade…',{exact:true}).waitFor({state:'hidden'});await p.getByRole('button',{name:'Salvar agendamento',exact:true}).click();await p.locator('[data-booking-created="true"]').waitFor();await p.reload();
  const data=await readApi(`/api/bookings?mode=manage&businessId=${b}&from=2026-11-16&to=2026-11-16`),bk=data.bookings.find(x=>x.professionalId==='pro-michele'&&x.time==='10:45');assert.equal(bk.durationMin,195);assert.equal(Date.parse(bk.endAt)-Date.parse(bk.startAt),195*60000);
  await p.locator('button').filter({hasText:'Consulta dermatológica'}).first().click();await p.getByText(/195 min · 3h15/).waitFor();await shot('booking195-reopened');
 });
 await test('temporary unavailability copy all scopes and professional save F5',async()=>{
  await agenda('2026-11-24');await p.getByRole('button',{name:'Bloquear horário',exact:true}).click();const box=await p.locator('[data-agenda-column-professional="pro-michele"]').boundingBox();await p.mouse.click(box.x+50,box.y+240*128/60);await p.getByText('Indisponibilidade temporária',{exact:true}).waitFor();
  for(const [scope,text] of [['business','Impede novos agendamentos para toda a clínica neste período.'],['professional','Bloqueia apenas a agenda do profissional selecionado.'],['resource','Impede que esse recurso seja reservado por outro atendimento.']]){await p.getByLabel(/^Escopo/).selectOption(scope);await p.getByText(text,{exact:true}).waitFor();await shot('block-copy-'+scope)}
  await p.getByLabel(/^Escopo/).selectOption('professional');await p.getByLabel(/^Profissional/).selectOption('pro-michele');await p.getByLabel('Início',{exact:true}).fill('12:00');await p.getByLabel('Fim',{exact:true}).fill('13:00');await p.getByLabel('Motivo (opcional)',{exact:true}).fill('Almoço');await p.getByRole('button',{name:'Criar bloqueio',exact:true}).click();await p.getByRole('heading',{name:'Bloquear horário',exact:true}).waitFor({state:'hidden'});await p.reload();const block=p.locator('[data-schedule-block]').filter({hasText:'Almoço'});assert.match(await block.innerText(),/12:00–13:00/);await block.click();assert.equal(await p.getByLabel('Fim',{exact:true}).inputValue(),'13:00');await shot('block-professional-reopened');
 });
 await test('special-day complement real save F5 and no duplicate blocks',async()=>{
  const before=await readApi(`/api/catalog/get?businessId=${b}`);await go('disponibilidade');const panel=p.locator('div.bg-white').filter({has:p.getByText('Dias especiais',{exact:true})}).last();await panel.getByLabel('DATA',{exact:true}).fill('2026-11-18');await panel.getByLabel(/^TIPO/).selectOption('special');await panel.getByLabel('DAS',{exact:true}).fill('13:00');await panel.getByLabel('ATÉ',{exact:true}).fill('18:00');await panel.getByLabel('MOTIVO (OPCIONAL)',{exact:true}).fill('Reunião');await panel.getByRole('button',{name:'Adicionar',exact:true}).click();await panel.getByText('18/11/2026 · 13:00–18:00',{exact:true}).waitFor();await p.reload();await p.getByText('18/11/2026 · 13:00–18:00',{exact:true}).waitFor();await shot('special-day-saved');
  for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:1100});await agenda('2026-11-18');const e=p.locator('[data-availability-exception]').first();await e.waitFor();assert.match(await e.innerText(),/09:00–13:00\s+INDISPONÍVEL\s+Reunião/);await shot('special-day-'+width)}
  const after=await readApi(`/api/catalog/get?businessId=${b}`);assert.equal(after.scheduleBlocks?.length,before.scheduleBlocks?.length);assert.ok(after.exceptions.some(x=>x.date==='2026-11-18'&&x.start==='13:00'&&x.end==='18:00'));
 });
 await test('special full closure is visible after save F5',async()=>{
  await p.setViewportSize({width:1440,height:1100});await go('disponibilidade');const panel=p.locator('div.bg-white').filter({has:p.getByText('Dias especiais',{exact:true})}).last();await panel.getByLabel('DATA',{exact:true}).fill('2026-11-19');await panel.getByLabel(/^TIPO/).selectOption('closed');await panel.getByLabel('MOTIVO (OPCIONAL)',{exact:true}).fill('Fechamento QA');await panel.getByRole('button',{name:'Adicionar',exact:true}).click();await panel.getByText('19/11/2026 · Fechado',{exact:true}).waitFor();await p.reload();await p.getByText('19/11/2026 · Fechado',{exact:true}).waitFor();await agenda('2026-11-19');const e=p.locator('[data-availability-exception]').first();await e.waitFor();assert.match(await e.innerText(),/INDISPONÍVEL\s+Fechamento QA/);await shot('special-day-closed');
 });
 await test('clean central discard at every viewport continue Escape discard',async()=>{
  for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:844});await go('equipe');await p.getByRole('button',{name:'Adicionar pessoa',exact:true}).click();await p.locator('#pessoa-nome').fill('Ana Polimento QA');await p.getByRole('button',{name:'Fechar',exact:true}).click();const modal=p.getByRole('alertdialog');await modal.waitFor();assert.equal(await modal.locator('svg').count(),0);let box=await modal.boundingBox();assert.ok(Math.abs(box.x+box.width/2-width/2)<4,JSON.stringify(box));await shot('discard-'+width);await p.getByRole('button',{name:'Continuar editando',exact:true}).click();assert.equal(await p.locator('#pessoa-nome').inputValue(),'Ana Polimento QA');await p.getByRole('button',{name:'Fechar',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[role=alertdialog]')?.contains(document.activeElement));await p.keyboard.press('Escape');await modal.waitFor({state:'hidden'});assert.equal(await modal.count(),0);await p.getByRole('button',{name:'Fechar',exact:true}).click();await p.getByRole('button',{name:'Descartar',exact:true}).click();await p.getByRole('heading',{name:'Adicionar pessoa',exact:true}).waitFor({state:'hidden'});}
 });
 await test('settings advanced closed resources feedback and curated theme persistence',async()=>{
  await p.setViewportSize({width:1440,height:1100});await go('configuracoes?tab=agenda');await p.getByText('Regras avançadas',{exact:true}).waitFor();assert.equal(await p.getByLabel(/^Preparação antes \(min\)/).isVisible(),false);assert.ok(!(await p.locator('body').innerText()).includes('intervalo legado'));await shot('settings-default');await p.getByText('Regras avançadas',{exact:true}).click();await p.getByLabel(/^Preparação antes \(min\)/).fill('5');await p.getByLabel(/^Tempo depois \(min\)/).fill('10');await p.getByRole('button',{name:'Salvar regras',exact:true}).click();await p.waitForTimeout(500);await p.reload();await p.getByText('Regras avançadas',{exact:true}).click();assert.equal(await p.getByLabel(/^Tempo depois \(min\)/).inputValue(),'10');await shot('settings-advanced-reopened');
  await p.route('**/api/schedule-operations', async route=>{if(route.request().method()==='POST')await new Promise(resolve=>setTimeout(resolve,600));await route.continue()});await p.getByLabel('Nome do recurso').fill('Ultrassom 01');await p.getByLabel('Tipo do recurso').selectOption('equipment');await p.getByRole('button',{name:'Adicionar recurso',exact:true}).click();await p.getByRole('button',{name:'Criando…',exact:true}).waitFor();await shot('resource-local-loading');await p.getByText('Ultrassom 01 · Equipamento',{exact:true}).waitFor();await p.reload();await p.getByText('Ultrassom 01 · Equipamento',{exact:true}).waitFor();await shot('resources-reopened');
  for(const id of ['azul-profundo','verde-equilibrado','teal-profundo','vinho','onix']){await go('configuracoes?tab=aparencia');await p.getByTestId('shell-appearance').waitFor();assert.equal(await p.locator('[data-testid^="nav-accent-"]:not([data-testid="nav-accent-preview"])').count(),5);await p.getByTestId('nav-accent-'+id).click();await p.waitForFunction(t=>localStorage.getItem('godoutor.nav-accent')===t,id);await p.reload();await p.waitForFunction(t=>document.querySelector(`[data-testid="nav-accent-${t}"]`)?.getAttribute('aria-pressed')==='true',id);await shot('theme-'+id);await go('perfil');assert.equal(await p.evaluate(()=>localStorage.getItem('godoutor.nav-accent')),id)}
 });
 await test('dashboard 100 real synthetic tasks capped four Ver todas all widths',async()=>{
  await p.evaluate(async businessId=>{for(let i=0;i<100;i++){const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,title:`Polimento pendência ${i}`,dueAt:'2026-11-01T12:00:00.000Z'})});if(!r.ok)throw Error('Task fixture HTTP '+r.status)}},b);
  for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:1100});await go('dashboard');const card=p.locator('section').filter({has:p.getByRole('heading',{name:'Conversas e tarefas',exact:true})}).last();await card.getByRole('link',{name:/Ver todas/}).waitFor();assert.equal(await card.getByText(/Polimento pendência/).count(),4);assert.ok(Number((await card.innerText()).match(/Ver todas \((\d+)\)/)?.[1])>=100);await card.scrollIntoViewIfNeeded();await shot('dashboard100-'+width);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true)}
 });
}finally{await fs.writeFile(dir+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));}
if(report.failures.length||report.console.length||report.network.length)process.exitCode=1;
