// Real mouse/keyboard/persistence QA. ONLY the disposable local production server.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { chromium } from 'playwright';
import { execSync } from 'node:child_process';
if(process.env.DATABASE_URL) throw Error('Remote DB forbidden');
const base='http://127.0.0.1:3000',b='andrioni-vet-qa',dir=process.env.QA_EVIDENCE_DIR||'.cache/pre-f1-p2';
await fs.mkdir(dir,{recursive:true});
const {default:c}=await import(process.env.QA_CHROMIUM_MODULE);
const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(x=>x!=='--single-process'),ignoreDefaultArgs:['--hide-scrollbars'],headless:true});
const report={head:execSync('git rev-parse HEAD').toString().trim(),checks:[],failures:[],console:[],network:[],screens:[],buttons:[],rawButtons:[],copy:[]};
const ok=s=>{report.checks.push(s);console.log('PASS',s);};
async function test(n,fn){if(process.env.QA_ONLY&&!n.includes(process.env.QA_ONLY))return;try{report.current=n;await fn();ok(n);}catch(e){report.failures.push({name:n,error:String(e),stack:e.stack});console.error('FAIL',n,String(e));await shot(p,'failure-'+n.replace(/\W/g,'-')).catch(()=>{});}}
async function shot(p,n){await p.screenshot({path:`${dir}/${n}.png`});report.screens.push(n+'.png');}
async function login(role){const ctx=await browser.newContext({viewport:{width:1440,height:1100},locale:'pt-BR'}),p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>report.console.push(String(e)));p.on('console',e=>{if(e.type()==='error')report.console.push(e.text());});p.on('response',r=>{report.network.push({scenario:report.current||'login/context',method:r.request().method(),status:r.status(),url:r.url()});});await p.goto(base+'/login');await p.locator('[type=email]').fill(role+'.qa@godoutor.local');await p.locator('[type=password]').fill('GodoutorQA2026!');await p.getByRole('button',{name:'Entrar',exact:true}).click();await p.waitForURL(/agenda|dashboard/);ok('Login '+role);return p;}
async function go(p,path){await p.goto(`${base}/${path}${path.includes('?')?'&':'?'}b=${b}`);}
async function agenda(p,view='day',date='2026-11-16'){await go(p,`agenda?data=${date}&view=${view}`);await p.locator('[data-agenda-column]').first().waitFor();}
async function drag(p,pro,start,end){const col=p.locator(`[data-agenda-column-professional="${pro}"]`);const box=await col.boundingBox();await p.mouse.move(box.x+50,box.y+(start-480)*128/60);await p.mouse.down();await p.mouse.move(box.x+50,box.y+(end-480)*128/60,{steps:25});await p.mouse.up();}
async function api(p,path){return p.evaluate(async u=>{const r=await fetch(u);if(!r.ok)throw Error(String(r.status));return r.json();},path);}
async function editMichelle(p){await go(p,'equipe');await p.locator('div.px-4.py-3').filter({has:p.getByText('Michelle',{exact:true})}).getByRole('button',{name:'GERENCIAR',exact:true}).click();await p.getByRole('heading',{name:'Gerenciar pessoa',exact:true}).waitFor();}
async function editService(p,name){await go(p,'servicos');await p.getByText(name,{exact:true}).locator('xpath=ancestor::div[.//button[normalize-space()="Editar"]][1]').getByRole('button',{name:'Editar',exact:true}).click();await p.getByRole('heading',{name:'Editar serviço',exact:true}).waitFor();}
const p=await login('owner');

async function post(path,data){return p.evaluate(async({path,data})=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));return v},{path,data})}
async function patient(){await p.getByRole('searchbox',{name:'Buscar cliente'}).fill('Ana');await p.getByRole('button',{name:/Ana Tutora QA/}).click();await p.getByLabel('Pet (paciente)',{exact:false}).selectOption('qa-pet')}
try{
 await test('P2 block 07 October 13:30 disabled single warning recovery save F5',async()=>{
  await agenda(p,'day','2026-10-07');await p.getByRole('button',{name:'Bloquear horário',exact:true}).click();await drag(p,'pro-michele',600,630);await p.getByLabel(/^Escopo/).selectOption('professional');await p.getByLabel(/^Profissional/).selectOption('pro-michele');await p.getByLabel('Início',{exact:true}).fill('13:00');await p.getByLabel('Fim',{exact:true}).fill('18:00');await p.getByLabel('Motivo (opcional)',{exact:true}).fill('P2 indisponível');await p.getByRole('button',{name:'Criar bloqueio',exact:true}).click();await p.getByRole('heading',{name:'Bloquear horário',exact:true}).waitFor({state:'hidden'});await p.reload();await p.locator('[data-schedule-block]').first().waitFor();
  const box=await p.locator('[data-agenda-column-professional="pro-michele"]').boundingBox();await p.mouse.click(box.x+2,box.y+(810-480)*128/60);await p.getByRole('heading',{name:'Novo agendamento',exact:true}).waitFor();await p.getByLabel('2. Serviço',{exact:false}).selectOption('svc-consulta');await patient();
  const warning=p.getByText('Este profissional não está disponível neste intervalo. Confira a disponibilidade, os atendimentos e os bloqueios.',{exact:true}),save=p.getByRole('button',{name:'Salvar agendamento',exact:true});await warning.waitFor();assert.equal(await warning.count(),1);assert.equal(await save.isDisabled(),true);assert.match(await p.getByTestId('booking-range-summary').innerText(),/13:30/);const count=report.network.filter(r=>r.method==='POST'&&r.url.endsWith('/api/bookings')).length;await save.evaluate(e=>e.click());assert.equal(await warning.count(),1);assert.equal(report.network.filter(r=>r.method==='POST'&&r.url.endsWith('/api/bookings')).length,count);await save.scrollIntoViewIfNeeded();await shot(p,'P2-A-blocked-single-disabled');
  await p.getByRole('button',{name:'09:00',exact:true}).click();await warning.waitFor({state:'hidden'});assert.equal(await save.isEnabled(),true);await save.scrollIntoViewIfNeeded();await shot(p,'P2-B-valid-enabled');await save.click();await p.locator('[data-booking-created="true"]').waitFor();await p.reload();await p.locator('button').filter({hasText:'Consulta clínica'}).first().click();await p.getByText(/09:00/).first().waitFor();await shot(p,'P2-B-saved-F5-reopened');const data=await api(p,`/api/bookings?mode=manage&businessId=${b}&from=2026-10-07&to=2026-10-07`);assert.ok(data.bookings.some(x=>x.time==='09:00'&&x.professionalId==='pro-michele'));assert.ok(!data.bookings.some(x=>x.time==='13:30'));
 });
 await test('P2 active service loses last eligible via Equipe and eligible service recovers',async()=>{
  await post('/api/catalog',{businessId:b,action:'service.save',name:'Consulta Simples',durationMin:30,price:0,active:true,bookable:true,professionalMode:'selected',professionalIds:['pro-michele']});await editMichelle(p);await p.getByLabel('Consulta Simples',{exact:false}).uncheck();await p.getByRole('button',{name:'Salvar alterações',exact:true}).click();await p.getByRole('heading',{name:'Gerenciar pessoa',exact:true}).waitFor({state:'hidden'});await p.reload();
  await go(p,'servicos');const row=p.getByText('Consulta Simples',{exact:true}).locator('xpath=ancestor::div[.//button[normalize-space()="Editar"]][1]');await row.getByText('Sem profissional habilitado',{exact:true}).waitFor();assert.equal(await row.getByText('Pode ser agendado',{exact:true}).count(),0);await row.getByText('Ativo',{exact:true}).waitFor();await shot(p,'P2-C-active-not-schedulable');const cat=await api(p,`/api/catalog/get?businessId=${b}`),s=cat.services.find(x=>x.name==='Consulta Simples');assert.equal(s.active,true);assert.deepEqual(s.professionalIds,[]);
  await agenda(p,'day','2026-11-16');await drag(p,'pro-michele',645,840);await p.getByLabel('2. Serviço',{exact:false}).selectOption(s.id);await p.getByText('Nenhum profissional está habilitado para este serviço.',{exact:true}).waitFor();assert.equal(await p.getByText('Nenhum profissional está habilitado para este serviço.',{exact:true}).count(),1);assert.equal(await p.getByText(/Fechado neste dia/).count(),0);assert.equal(await p.getByRole('button',{name:'Salvar agendamento',exact:true}).isDisabled(),true);await shot(p,'P2-C-no-eligible-correct-message');
  await p.getByLabel('2. Serviço',{exact:false}).selectOption('svc-consulta');await p.getByText('Nenhum profissional está habilitado para este serviço.',{exact:true}).waitFor({state:'hidden'});await p.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='Salvar agendamento')?.disabled);await patient();assert.match(await p.getByTestId('booking-range-summary').innerText(),/195 min · 3h15/);for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:width===390?844:1100});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await shot(p,'P2-D-E-range-'+width)}await p.setViewportSize({width:1440,height:1100});await p.getByRole('button',{name:'Salvar agendamento',exact:true}).click();await p.locator('[data-booking-created="true"]').waitFor();await p.reload();const bookings=await api(p,`/api/bookings?mode=manage&businessId=${b}&from=2026-11-16&to=2026-11-16`);assert.ok(bookings.bookings.some(x=>x.durationMin===195&&x.time==='10:45'));await shot(p,'P2-D-eligible-saved-F5');
 });
 await test('empty professional warning save reload no linkage',async()=>{
  await p.setViewportSize({width:1440,height:1100});await go(p,'equipe');await p.getByRole('button',{name:'Adicionar pessoa',exact:true}).click();await p.locator('#pessoa-nome').fill('Profissional Sem Serviço QA');await p.getByRole('checkbox',{name:/Realiza atendimentos/}).check();await p.getByText(/Este profissional será criado sem procedimentos habilitados/).waitFor();await shot(p,'empty-pro-warning');await p.getByRole('button',{name:'Adicionar pessoa',exact:true}).last().click();await p.getByRole('heading',{name:'Adicionar pessoa',exact:true}).waitFor({state:'hidden'});await p.reload();const row=p.locator('div.px-4.py-3').filter({has:p.getByText('Profissional Sem Serviço QA',{exact:true})});await row.getByRole('button',{name:'GERENCIAR',exact:true}).click();assert.equal(await p.locator('label').filter({hasText:'Consulta clínica'}).locator('input[type=checkbox]').isChecked(),false);await shot(p,'empty-pro-reopened');const cat=await api(p,`/api/catalog/get?businessId=${b}`);const pro=cat.professionals.find(x=>x.name==='Profissional Sem Serviço QA');assert.ok(pro);assert.ok(!('serviceIds' in pro));assert.ok(cat.services.every(s=>s.professionalMode==='selected'&&!s.professionalIds.includes(pro.id)));await agenda(p);await drag(p,pro.id,660,690);await p.getByLabel('2. Serviço',{exact:false}).selectOption('svc-consulta');await p.getByText(/Profissional Sem Serviço QA não realiza este serviço/).waitFor();await shot(p,'empty-pro-no-appointment');
 });
 await test('clinic and resource blocks day week exact labels',async()=>{
  await go(p,'configuracoes?tab=agenda');await p.getByLabel('Nome do recurso').fill('Sala Cirúrgica QA');await p.getByRole('button',{name:'Adicionar recurso',exact:true}).click();await p.getByText('Sala Cirúrgica QA · Sala',{exact:true}).waitFor();await p.reload();await p.getByText('Sala Cirúrgica QA · Sala',{exact:true}).waitFor();
  for(const [scope,reason,start,end] of [['business','Reunião da equipe','14:00','15:30'],['resource','Manutenção','10:00','12:00']]){
   await agenda(p,'day','2026-11-23');await p.getByRole('button',{name:'Bloquear horário',exact:true}).click();await drag(p,'pro-hernani',600,660);await p.getByLabel(/^Escopo/).selectOption(scope);await p.getByLabel('Início',{exact:true}).fill(start);await p.getByLabel('Fim',{exact:true}).fill(end);if(scope==='resource')await p.getByLabel(/^Recurso/).selectOption({label:'Sala Cirúrgica QA'});await p.getByLabel('Motivo (opcional)',{exact:true}).fill(reason);await p.getByRole('button',{name:'Criar bloqueio',exact:true}).click();await p.getByRole('heading',{name:'Bloquear horário',exact:true}).waitFor({state:'hidden'});await p.reload();
   for(const view of ['day','week']){await agenda(p,view,'2026-11-23');const block=p.locator('[data-schedule-block]').filter({hasText:reason}).first();await block.waitFor();const text=await block.innerText();for(const s of [start+'–'+end,'BLOQUEIO',reason,scope==='business'?'Clínica':'Sala Cirúrgica QA'])assert.ok(text.includes(s),text);await block.scrollIntoViewIfNeeded();await shot(p,`block-${scope}-${view}`);}
  }
 });
 await test('buttons normal hover seven pages both themes and copy sweep',async()=>{
  for(const theme of ['azul-profundo','verde-equilibrado']){
   await go(p,'configuracoes?tab=aparencia');await p.getByTestId('nav-accent-'+theme).click();await p.waitForFunction(t=>localStorage.getItem('godoutor.nav-accent')===t,theme);await p.reload();await p.waitForFunction(t=>document.querySelector(`[data-testid="nav-accent-${t}"]`)?.getAttribute('aria-pressed')==='true',theme);
   for(const route of ['agenda?data=2026-11-16','clientes','clientes/qa-tutor','servicos','equipe','configuracoes?tab=agenda','perfil']){
    // Contact360 route uses the canonical people360 key from the actual row.
    if(route==='clientes/qa-tutor'){await go(p,'clientes');await p.getByText('Ana Tutora QA',{exact:true}).first().click();await p.getByRole('link',{name:'WhatsApp',exact:true}).waitFor();}else await go(p,route);
    await p.waitForTimeout(450);const body=await p.locator('body').innerText();const bad=body.match(/página pública|captadas na página|interesses da página|link na bio|\bloja\b|\bprodutos?\b|\bpedidos?\b|promoções|sua página|cadastros na página/ig)||[];report.copy.push({route,theme,bad});assert.deepEqual(bad,[]);
    report.rawButtons.push({route,theme,items:await p.locator('.workspace-main-col button:not(.il-control),.workspace-main-col a:not(.il-control)').evaluateAll(els=>els.filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>({label:e.innerText||e.getAttribute('aria-label'),role:e.getAttribute('role'),class:e.className})))});
    const controls=p.locator('button.il-control,a.il-control');let audited=0,hoverShot=false;
    for(let i=0;i<await controls.count();i++){
     const el=controls.nth(i);if(!await el.isVisible()||!await el.isEnabled())continue;const cls=await el.getAttribute('class');const secondary=cls.includes('border-[var(--brand)]'),wa=cls.includes('bg-emerald-50')&&cls.includes('text-emerald-800'),primary=cls.includes('bg-[var(--accent)]');if(!secondary&&!wa&&!primary)continue;
     await p.mouse.move(0,0);await p.waitForTimeout(180);const normal=await el.evaluate(e=>{const s=getComputedStyle(e);return {bg:s.backgroundColor,border:s.borderTopColor,width:s.borderTopWidth,color:s.color};});await el.hover();await p.waitForTimeout(180);const hover=await el.evaluate(e=>{const s=getComputedStyle(e);return {bg:s.backgroundColor,border:s.borderTopColor,width:s.borderTopWidth,color:s.color};});if(secondary)assert.equal(normal.bg,'rgba(0, 0, 0, 0)');else assert.notEqual(normal.bg,'rgba(0, 0, 0, 0)');assert.notEqual(normal.width,'0px');if(secondary||wa){assert.equal(hover.border,normal.border);assert.equal(hover.width,normal.width);if(secondary)assert.notEqual(hover.bg,'rgba(0, 0, 0, 0)');else assert.equal(hover.bg,'rgba(0, 0, 0, 0)');}else assert.notEqual(hover.bg,'rgba(0, 0, 0, 0)');if(wa)assert.equal(normal.bg,'rgb(240, 253, 244)');if(!hoverShot&&secondary){await shot(p,`hover-${route.replace(/\W/g,'-')}-${theme}`);hoverShot=true;}report.buttons.push({route,theme,label:await el.innerText(),normal,hover});audited++;
    }
    assert.ok(audited>0,route);await p.mouse.move(0,0);await shot(p,`buttons-${route.replace(/\W/g,'-')}-${theme}`);
   }
  }
 });
 await test('special-day complement real save F5 and no duplicate blocks',async()=>{
  const before=await api(p,`/api/catalog/get?businessId=${b}`);await go(p,'disponibilidade');const panel=p.locator('div.bg-white').filter({has:p.getByText('Dias especiais',{exact:true})}).last();await panel.getByLabel('DATA',{exact:true}).fill('2026-11-18');await panel.getByLabel(/^TIPO/).selectOption('special');await panel.getByLabel('DAS',{exact:true}).fill('13:00');await panel.getByLabel('ATÉ',{exact:true}).fill('18:00');await panel.getByLabel('MOTIVO (OPCIONAL)',{exact:true}).fill('Reunião');await panel.getByRole('button',{name:'Adicionar',exact:true}).click();await panel.getByText('18/11/2026 · 13:00–18:00',{exact:true}).waitFor();await p.reload();await p.getByText('18/11/2026 · 13:00–18:00',{exact:true}).waitFor();await shot(p,'special-day-saved');
  for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:1100});await agenda(p,'day','2026-11-18');const e=p.locator('[data-availability-exception]').first();await e.waitFor();assert.match(await e.innerText(),/09:00–13:00\s+INDISPONÍVEL\s+Reunião/);await shot(p,'special-day-'+width)}
  const after=await api(p,`/api/catalog/get?businessId=${b}`);assert.equal(after.scheduleBlocks?.length,before.scheduleBlocks?.length);assert.ok(after.exceptions.some(x=>x.date==='2026-11-18'&&x.start==='13:00'&&x.end==='18:00'));
 });
 await test('dashboard 100 real synthetic tasks capped four Ver todas all widths',async()=>{
  await p.evaluate(async businessId=>{for(let i=0;i<100;i++){const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,title:`Polimento pendência ${i}`,dueAt:'2026-11-01T12:00:00.000Z'})});if(!r.ok)throw Error('Task fixture HTTP '+r.status)}},b);
  for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:1100});await go(p,'dashboard');const card=p.locator('section').filter({has:p.getByRole('heading',{name:'Conversas e tarefas',exact:true})}).last();await card.getByRole('link',{name:/Ver todas/}).waitFor();assert.equal(await card.getByText(/Polimento pendência/).count(),4);assert.ok(Number((await card.innerText()).match(/Ver todas \((\d+)\)/)?.[1])>=100);await card.scrollIntoViewIfNeeded();await shot(p,'dashboard100-'+width);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true)}
 });
 await test('settings save request and context after F5',async()=>{await p.setViewportSize({width:1440,height:1100});await go(p,'configuracoes?tab=agenda');await p.getByLabel(/^Antecedência mínima/).fill('0');const response=p.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/api/'));await p.getByRole('button',{name:'Salvar regras',exact:true}).click();assert.equal((await response).ok(),true);await p.reload();assert.equal(await p.getByLabel(/^Antecedência mínima/).inputValue(),'0');await shot(p,'settings-saved-F5')});
}finally{report.unexpected=report.network.filter(r=>r.status>=400);report.expectedValidation=[];await fs.writeFile(dir+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({checks:report.checks,failures:report.failures,console:report.console,unexpected:report.unexpected,requests:report.network.length},null,2))}
if(report.failures.length||report.console.length||report.unexpected.length)process.exitCode=1;
