// ONLY against a disposable local Next production server. Never a preview/production DB.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { chromium } from 'playwright';
const base='http://127.0.0.1:3000', b='andrioni-vet-qa',date=process.env.QA_DATE||'2026-10-12';
if(process.env.DATABASE_URL)throw Error('DATABASE_URL forbidden');
const {default:c}=await import(process.env.QA_CHROMIUM_MODULE);
const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(x=>x!=='--single-process'),headless:true,ignoreDefaultArgs:['--hide-scrollbars']});
const dir=process.env.QA_EVIDENCE_DIR||'.cache/pre-f1-final';await fs.mkdir(dir,{recursive:true});
const report={checks:[],failures:[],console:[],network:[],screens:[]};
const ok=s=>{report.checks.push(s);console.log('PASS',s);};
async function shot(p,n){await p.screenshot({path:`${dir}/${n}.png`});report.screens.push(n+'.png');}
async function scenario(name,fn){if(process.env.QA_ONLY&&!name.includes(process.env.QA_ONLY))return;try{await fn();ok(name);}catch(e){report.failures.push({name,error:String(e)});console.error('FAIL',name,String(e));}}
async function login(role){const ctx=await browser.newContext({viewport:{width:1440,height:1600}}),p=await ctx.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>report.console.push(String(e)));p.on('console',e=>{if(e.type()==='error')report.console.push(e.text());});p.on('response',r=>{if(r.status()>=400)report.network.push({status:r.status(),url:r.url()});});await p.goto(base+'/login');await p.locator('[type=email]').fill(role+'.qa@godoutor.local');await p.locator('[type=password]').fill('GodoutorQA2026!');await p.getByRole('button',{name:'Entrar',exact:true}).click();await p.waitForURL(/agenda|dashboard/);ok('Real login '+role);return p;}
const go=async(p,path)=>{await p.goto(`${base}/${path}${path.includes('?')?'&':'?'}b=${b}`);};
async function agenda(p,view='day',day=date){await go(p,`agenda?data=${day}&view=${view}`);await p.locator('[data-agenda-column]').first().waitFor();}
async function drag(p,from,to,pro='pro-hernani'){const box=await p.locator(`[data-agenda-column-professional="${pro}"]`).boundingBox();await p.mouse.move(box.x+60,box.y+(from-480)*128/60);await p.mouse.down();await p.mouse.move(box.x+60,box.y+(to-480)*128/60,{steps:20});await p.mouse.up();}
async function close(p){await p.getByRole('button',{name:'Fechar',exact:true}).first().click();}
async function json(p,path){return p.evaluate(async u=>{const r=await fetch(u);if(!r.ok)throw Error(String(r.status));return r.json();},path);}
const p=await login('owner');
try{
 await scenario('Hernani 09:15–12:45 / 210 min / service30 / UTC / success',async()=>{
  await agenda(p);await drag(p,555,765);await p.getByRole('heading',{name:'Novo agendamento',exact:true}).waitFor();
  assert.match(await p.getByTestId('booking-range-summary').innerText(),/Início\s+09:15\s+Fim\s+12:45\s+Duração\s+210 min · 3h30/);assert.equal(await p.getByTestId('agenda-selected-range').count(),1);
  assert.equal(await p.getByLabel('Duração deste atendimento em minutos').isVisible(),false);await shot(p,'01-range-210-closed');
  await p.getByText('Opções avançadas',{exact:true}).click();assert.equal(await p.getByLabel('Duração deste atendimento em minutos').inputValue(),'210');await shot(p,'02-advanced');await p.getByText('Opções avançadas',{exact:true}).click();
  await p.getByRole('searchbox',{name:'Buscar cliente'}).fill('Ana');await p.getByRole('button',{name:/Ana Tutora QA/}).click();await p.getByLabel('Pet (paciente)',{exact:false}).selectOption('qa-pet');await p.getByLabel('2. Serviço',{exact:false}).selectOption('svc-consulta');
  await p.getByText('Verificando disponibilidade…',{exact:true}).waitFor({state:'hidden'});assert.equal(await p.getByRole('button',{name:'09:15',exact:true}).count(),0);await p.getByRole('button',{name:'Salvar agendamento',exact:true}).click();await p.locator('[data-booking-created="true"]').waitFor();await shot(p,'03-success');
  const d=await json(p,`/api/bookings?mode=manage&businessId=${b}&from=${date}&to=${date}`),bk=d.bookings.find(x=>x.professionalId==='pro-hernani'&&x.time==='09:15');assert.equal(bk.durationMin,210);assert.equal(Date.parse(bk.endAt)-Date.parse(bk.startAt),210*60000);await close(p);
 });
 await scenario('Hernani block13–17:30 Cirurgia Day+Week and edit',async()=>{
  await agenda(p);await p.getByRole('button',{name:'Bloquear horário',exact:true}).click();await drag(p,780,1050);await p.getByRole('heading',{name:'Bloquear horário',exact:true}).waitFor();assert.equal(await p.getByLabel('Início',{exact:true}).inputValue(),'13:00');assert.equal(await p.getByLabel('Fim',{exact:true}).inputValue(),'17:30');await p.getByLabel('Motivo (opcional)',{exact:true}).fill('Cirurgia');await p.getByRole('button',{name:'Criar bloqueio',exact:true}).click();await p.getByRole('heading',{name:'Bloquear horário',exact:true}).waitFor({state:'hidden'});
  await p.locator('[data-schedule-block]').filter({hasText:'Cirurgia'}).waitFor();await shot(p,'04-block-day');await agenda(p,'week');const card=p.locator('[data-schedule-block]').filter({hasText:'Cirurgia'});await card.waitFor();assert.match(await card.innerText(),/13:00–17:30/);assert.match(await card.innerText(),/Hernani/);await shot(p,'05-block-week');await card.click();await p.getByLabel('Início',{exact:true}).waitFor();assert.equal(await p.getByLabel('Fim',{exact:true}).inputValue(),'17:30');await shot(p,'06-block-edit');
 });
 await scenario('Library scrollbar / dermatology BRL90 30min Michelle / group persistence',async()=>{
  await go(p,'servicos');await p.getByRole('button',{name:'Novo serviço',exact:true}).click();const combo=p.getByRole('combobox',{name:'Serviço / procedimento'});await combo.focus();const list=p.getByRole('listbox',{name:'Biblioteca veterinária'});await list.waitFor();let box=await list.boundingBox();await p.mouse.move(box.x+box.width-2,box.y+20);await p.mouse.down();await p.mouse.move(box.x+box.width-2,box.y+120,{steps:8});await p.mouse.up();await p.waitForTimeout(250);assert.equal(await list.isVisible(),true);await list.hover();await p.mouse.wheel(0,350);await p.waitForTimeout(200);assert.equal(await list.isVisible(),true);await shot(p,'07-service-scroll');
  await combo.fill('dermato');await p.getByRole('option').filter({hasText:'Consulta dermatológica'}).click();await p.getByPlaceholder('Opcional — ex: 120,00').fill('90,00');await p.getByLabel('Duração padrão em minutos').fill('30');await p.getByLabel('Somente profissionais selecionados').check();await p.getByRole('button',{name:'Michelle',exact:true}).click();assert.equal(await p.getByLabel('Preparação antes (min)').isVisible(),false);await shot(p,'08-dermatology-group');await p.getByRole('button',{name:'Salvar serviço',exact:true}).click();await p.getByRole('heading',{name:'Novo serviço',exact:true}).waitFor({state:'hidden'});
  await p.getByText('Consulta dermatológica',{exact:true}).locator('xpath=ancestor::div[.//button[normalize-space()="Editar"]][1]').getByRole('button',{name:'Editar',exact:true}).click();await p.getByRole('heading',{name:'Editar serviço',exact:true}).waitFor();assert.equal(await p.getByPlaceholder('Opcional — ex: 120,00').inputValue(),'90,00');assert.equal(await p.getByLabel('Duração padrão em minutos').inputValue(),'30');assert.match(await p.getByRole('button',{name:'Michelle',exact:true}).getAttribute('class'),/bg-emerald-50/);await shot(p,'09-service-reopened');
 });
 await scenario('Michelle canonical team linkage',async()=>{await go(p,'equipe');await p.locator('div.px-4.py-3').filter({has:p.getByText('Michelle',{exact:true})}).getByRole('button',{name:'GERENCIAR',exact:true}).click();await p.getByRole('heading',{name:'Gerenciar pessoa',exact:true}).waitFor();assert.equal(await p.getByLabel('Consulta dermatológica',{exact:false}).isChecked(),true);await shot(p,'10-michelle-team');});
 await scenario('Ana dirty draft outside / continue / Escape / discard',async()=>{
  await go(p,'equipe');await p.getByRole('button',{name:'Adicionar pessoa',exact:true}).click();await p.locator('#pessoa-nome').fill('Ana Souza');await p.locator('#pessoa-email').fill('ana.qa@godoutor.local');await p.locator('#pessoa-telefone').fill('88888888888');await p.getByRole('checkbox',{name:/Tem acesso/}).check();assert.equal(await p.getByRole('button',{name:/^Recepção/}).getAttribute('aria-pressed'),'true');await shot(p,'11-ana-draft');const backdrop=await p.locator('.gd-team-editor > div > div[aria-hidden="true"]').boundingBox();await p.mouse.click(backdrop.x+20,500);await p.getByRole('heading',{name:'Descartar alterações?',exact:true}).waitFor();await shot(p,'12-ana-guard');await p.getByRole('button',{name:'Continuar editando',exact:true}).click();assert.equal(await p.locator('#pessoa-nome').inputValue(),'Ana Souza');assert.equal(await p.locator('#pessoa-email').inputValue(),'ana.qa@godoutor.local');assert.equal((await p.locator('#pessoa-telefone').inputValue()).replace(/\D/g,''),'88888888888');await p.keyboard.press('Escape');await p.getByRole('heading',{name:'Descartar alterações?',exact:true}).waitFor();await p.getByRole('button',{name:'Descartar',exact:true}).click();await p.getByRole('heading',{name:'Adicionar pessoa',exact:true}).waitFor({state:'hidden'});
 });
 for(const theme of ['azul-profundo','verde-equilibrado'])await scenario('Theme '+theme+' F5 / secondary / WhatsApp green',async()=>{
  await go(p,'configuracoes?tab=aparencia');await p.getByTestId('nav-accent-'+theme).click();await p.waitForFunction(t=>localStorage.getItem('godoutor.nav-accent')===t,theme);await p.reload();await p.waitForFunction(t=>document.querySelector(`[data-testid="nav-accent-${t}"]`)?.getAttribute('aria-pressed')==='true',theme);await shot(p,`13-config-${theme}`);
  await go(p,'clientes');await p.getByText('Ana Tutora QA',{exact:true}).first().click();await p.getByRole('link',{name:'WhatsApp',exact:true}).waitFor();assert.equal(await p.getByRole('link',{name:'WhatsApp',exact:true}).evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(240, 253, 244)');await shot(p,`14-client-${theme}`);
 });
 for(const role of ['recepcao','orlando'])await scenario(role+' scope and navigation',async()=>{const r=await login(role);await agenda(r);assert.equal(await r.locator('[data-agenda-column]').count(),role==='orlando'?1:3);if(role==='recepcao')assert.equal(await r.locator('nav a[href*="/funil"]').count(),0);await shot(r,'15-'+role);await r.context().close();});
}finally{await fs.writeFile(dir+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));}
if(report.failures.length||report.console.length||report.network.length)process.exitCode=1;
