import './helpers/temp-db';
import { beforeEach,describe,expect,it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { NextRequest } from 'next/server';
import { emptyDB,readDB,writeDB,updateDB } from '../db';
import { createSession,hashPassword } from '../auth';
import { GET,POST,DELETE } from '@/app/api/entity-deletion/route';
import { biz } from './helpers/automation-fixtures';
import { defaultBlocks,defaultTheme,defaultPresetId } from '../templates';
import { deletionImpact } from '../entity-deletion';
const password='Synthetic-correct-password!';let userId='',token='';
const target={kind:'business',id:'empty',organizationId:'org',name:'Filial de teste'};
function req(method:string,body:any={},headers:Record<string,string>={}) {return new NextRequest(`http://localhost/api/entity-deletion${method==='GET'?'?'+new URLSearchParams(body):''}`,{method,headers:{Authorization:`Bearer ${token}`,Origin:'http://localhost',Host:'localhost','Content-Type':'application/json','X-Instalink-Action':'delete-empty-entity',...headers},...(method==='GET'?{}:{body:JSON.stringify(body)})});}
async function authorize(t=target){const res=await POST(req('POST',{...t,password}));expect(res.status).toBe(200);return (await res.json()).token;}
beforeEach(async()=>{userId=randomUUID();const db=emptyDB();db.users.push({id:userId,name:'Owner',email:`${userId}@example.invalid`,passwordHash:hashPassword(password),role:'owner',createdAt:new Date().toISOString()});db.organizations.push({id:'org',ownerId:userId,name:'Organização teste',metadata:{},createdAt:'',updatedAt:''},{id:'foreign',ownerId:'stranger',name:'Alheia',metadata:{},createdAt:'',updatedAt:''});db.businesses.push(biz('empty',{name:target.name,ownerId:userId,organizationId:'org',published:false,hours:{}}),biz('other',{name:'Outro alvo',ownerId:userId,organizationId:'org',published:false,hours:{}}),biz('foreign-b',{ownerId:'stranger',organizationId:'foreign'}));await writeDB(db);token=await createSession(userId);});
describe('Protected empty-entity deletion — actual authenticated routes',()=>{
 it('computes impact on server and deletes an empty synthetic unit once, retaining audit',async()=>{const preview=await GET(req('GET',target));expect((await preview.json()).allowed).toBe(true);const grant=await authorize();const r=await DELETE(req('DELETE',{...target,token:grant}));expect(r.status).toBe(200);expect((await readDB()).businesses.some(b=>b.id===target.id)).toBe(false);expect((await readDB()).organizations.some(o=>o.id==='org')).toBe(true);expect((await DELETE(req('DELETE',{...target,token:grant}))).status).not.toBe(200);expect((await readDB()).audit.filter(a=>a.action==='entity.deleted')).toHaveLength(1);});
 it('requires the real password, not a frontend confirmation flag',async()=>{expect((await POST(req('POST',{...target,password:'incorrect',passwordConfirmed:true}))).status).toBe(400);expect((await POST(req('POST',{...target,passwordConfirmed:true}))).status).toBe(400);expect((await readDB()).businesses).toHaveLength(3);});
 it('enforces persisted password attempt limit across new authorization attempts',async()=>{for(let i=0;i<5;i++)expect((await POST(req('POST',{...target,password:'wrong'}))).status).toBe(400);expect((await POST(req('POST',{...target,password}))).status).toBe(429);});
 it.each(['https://evil.example','http://other.localhost','https://localhost'])('rejects cross-origin %s',async origin=>{expect((await POST(req('POST',{...target,password},{Origin:origin}))).status).toBe(403);});
 it('rejects missing CSRF action header and missing origin',async()=>{expect((await POST(req('POST',{...target,password},{'X-Instalink-Action':''}))).status).toBe(403);expect((await DELETE(req('DELETE',{...target,token:'ignored'},{Origin:''}))).status).toBe(403);});
 it('rejects non-owners, including administrators and platform master',async()=>{await updateDB(db=>{db.organizations[0].ownerId='real-owner';db.businesses[0].ownerId='real-owner';db.organizationMembers.push({id:'m',organizationId:'org',userId,role:'ADMIN',active:true,createdAt:'',updatedAt:''});});expect((await GET(req('GET',target))).status).toBe(403);expect((await POST(req('POST',{...target,password}))).status).toBe(403);await updateDB(db=>{db.users[0].role='master';db.organizations[0].ownerId=userId;db.businesses[0].ownerId=userId;});expect((await POST(req('POST',{...target,password}))).status).toBe(403);});
 it('rejects another organization and wrong organization scope',async()=>{expect((await POST(req('POST',{...target,id:'foreign-b',organizationId:'foreign',password}))).status).toBe(403);expect((await POST(req('POST',{...target,organizationId:'foreign',password}))).status).toBe(403);});
 it('binds grants to target, action, session and exact name',async()=>{const grant=await authorize();expect((await DELETE(req('DELETE',{...target,id:'other',name:'Outro alvo',token:grant}))).status).toBe(409);expect((await DELETE(req('DELETE',{...target,kind:'organization',id:'org',name:'Organização teste',token:grant}))).status).toBe(409);const another=await createSession(userId);expect((await DELETE(req('DELETE',{...target,token:grant},{Authorization:`Bearer ${another}`}))).status).toBe(409);expect((await DELETE(req('DELETE',{...target,name:'wrong',token:grant}))).status).toBe(400);});
 it('expires reauthentication and rejects token-only unauthenticated requests',async()=>{const grant=await authorize();await updateDB(db=>{db.deletionAuthorizations![0].expiresAt=Date.now()-1;});expect((await DELETE(req('DELETE',{...target,token:grant}))).status).toBe(409);expect((await DELETE(req('DELETE',{...target,token:grant},{Authorization:''}))).status).toBe(401);});
 it('rechecks new dependencies and ownership at execution',async()=>{const grant=await authorize();await updateDB(db=>{db.contacts.push({id:'patient',businessId:target.id,createdAt:new Date().toISOString()} as any);});expect((await DELETE(req('DELETE',{...target,token:grant}))).status).toBe(409);await updateDB(db=>{db.organizations[0].ownerId='someone-else';});expect((await DELETE(req('DELETE',{...target,token:grant}))).status).toBe(403);expect((await readDB()).contacts).toHaveLength(1);});
 it('serializes repeated concurrent requests: exactly one mutation',async()=>{const grant=await authorize();const replies=await Promise.all([DELETE(req('DELETE',{...target,token:grant})),DELETE(req('DELETE',{...target,token:grant}))]);expect(replies.filter(r=>r.status===200)).toHaveLength(1);expect((await readDB()).audit.filter(a=>a.action==='entity.deleted')).toHaveLength(1);});
 it('blocks organization deletion with linked units, but deletes a genuinely empty organization',async()=>{const t={kind:'organization',id:'org',organizationId:'org',name:'Organização teste'};expect((await POST(req('POST',{...t,password}))).status).toBe(409);await updateDB(db=>{db.organizations.push({id:'blank',name:'Vazia',ownerId:userId,metadata:{},createdAt:'',updatedAt:''});});const empty={...t,id:'blank',organizationId:'blank',name:'Vazia'};const grant=await authorize(empty);expect((await DELETE(req('DELETE',{...empty,token:grant}))).status).toBe(200);expect((await readDB()).businesses).toHaveLength(3);});
 it('removes only untouched default page config; edited page is a dependency even with identical timestamp',async()=>{await updateDB(db=>{const b=db.businesses[0];db.pages.push({id:'page',businessId:b.id,presetId:defaultPresetId(b.niche),theme:defaultTheme(b.niche),blocks:defaultBlocks(b.niche,b.modes),updatedAt:b.createdAt});});expect((await(await GET(req('GET',target))).json()).allowed).toBe(true);await updateDB(db=>{db.pages[0].blocks[0].settings={title:'Custom content'};});expect((await(await GET(req('GET',target))).json()).allowed).toBe(false);});
 it('never logs passwords or bearer grants',async()=>{const grant=await authorize();await DELETE(req('DELETE',{...target,token:grant}));const db=await readDB();expect(JSON.stringify(db)).not.toContain(password);expect(JSON.stringify(db.audit)).not.toContain(grant);});
 for(const table of ['contacts','bookings','encounters','orders','queue','services','professionals','availability','exceptions','members','agents','conversations','messages','campaigns','campaignRecipients','automations','automationRuns','tasks','aiProposals','integrations','integrationEvents','apiKeys','webhooks','webhookDeliveries','pipelines','leads','reviews','events','idempotencyKeys','financialRecords']) {
   it(`dependency inventory blocks ${table}, including future collections`,async()=>{const db=await readDB();(db as any)[table]=[{id:'dependency',businessId:'empty'}];expect(deletionImpact(db,'business','empty').blockers.some(b=>b.type===table)).toBe(true);});
 }
});
